### ISSUE TITLE
Fix dungeon chest loots

### ISSUE THREAD

**Issue by hron84** [AllTheMods/tfc#14]
Some spider/zombie spawner rooms do spawn in the caves, which is nice. However, loot chests contains a little nonsenses

 - Remove vanilla copper ore or replace with TFC ore (vanilla ore can be processed in very late state, but the copper would be useful)
 - Same for vanilla copper ingot - TFC copper would be better...

**Comment by thevortex** [comment]
will have another update out before the weekend with this and other mc ingots that were overlooked replaced with TFC variants. thanks!

**Comment by thevortex** [comment]
swapped as many things as i could think of in the 1.2 update, copper, iron, gold diamond, etc if you are still finding any please let me know :)
