### ISSUE TITLE
Underwater bug

### ISSUE THREAD

**Issue by FlmingDraogGming** [AllTheMods/tfc#16]
So I'm down mining Bismuthinite in a cave and I found some underwater and I jump in the water to go and get it. I then find myself taking fall damage and not having any air bubbles, its like the game is treating me as I am not underwater
![Underwaterbug](https://user-images.githubusercontent.com/124545670/216877956-8c7203db-04ce-49f7-bdd3-69489c94558b.png)
![Underwaterbug2](https://user-images.githubusercontent.com/124545670/216877739-fcc20dc0-f311-460b-ac16-8e63ac658aa5.png)

**Comment by AzeznLadyofFloof** [comment]
Yup, it's also lagging my server hardcore.. the way the water moves fucks with the shaders as well. Any fixes?
