### ISSUE TITLE
Crash after feeding sheep

### ISSUE THREAD

**Issue by henriquesw** [AllTheMods/tfc#19]
My game is crashing after feeding a sheep with oat

I'm using version 1.6
[hs_err_pid8824.log](https://github.com/AllTheMods/tfc/files/10724151/hs_err_pid8824.log)

**Comment by thevortex** [comment]
make sure your graphics drivers are fully updated. this is a gpu driver crash

**Comment by henriquesw** [comment]
My driver is already at the latest version, after I updated to 1.7 it stopped happening
