### ISSUE TITLE
Weak steel mixing bugged

### ISSUE THREAD

**Issue by Nidaelie** [AllTheMods/tfc#20]
Just tried 2 times to mix in a crucible steel  + nickel + black bronze and im getting unknown mix.

tried 8 steel 4 nickel 4 black bronze and bugged

tried 10 steel 4 nickel 4 black bronze and bugged too.

according to tfc documentation the % are inside the values for the mix

**Comment by thevortex** [comment]
Nickel 15-25%
Black Bronze 15-25%
Steel 50-70%
6 steel 2 black bronze 2 nickel is a working ratio

**Comment by Nidaelie** [comment]
added 2 steel to the mix to make 12 steel 4 nickel and 4 black bronze and not working mate
