### ISSUE TITLE
Create mechanical press deletes heated ingots

### ISSUE THREAD

**Issue by ganagal** [AllTheMods/tfc#26]
When you place an ingot that has been heated (like if it has just been cast or taken out of a crucible) under a mechanical press they get voided (this is on a server in v1.3)

video:
https://youtu.be/pOCh2B1R3wY

**Comment by ganagal** [comment]
also happens in latest version (1.7)

**Comment by thevortex** [comment]
for mechanical press recipes from create, the items do need to be cooled prior to pressing. IE Metal Presses can work on hot metals
