### ISSUE TITLE
Immersive Engineering Dropping Conveyor Belt Recipe issue.

### ISSUE THREAD

**Issue by skcuf** [AllTheMods/tfc#69]
The recipe for the IE dropping conveyor belt requires the 'Iron Trapdoor,' but one can only craft the 'Wrought Iron Trapdoor.' The wrought iron trapdoor does not work in the recipe. Perhaps this is by design and I'm supposed to find an iron trapdoor, but I have doubts.

![Immersive_Conveyor_Recipe](https://user-images.githubusercontent.com/13948660/235975984-84d9eb1d-5480-4c5d-bb59-113cb34abe70.png)
Recipe for creation

![Immersive_Conveyor_Recipe2](https://user-images.githubusercontent.com/13948660/235976072-24ef7016-96b1-4892-bcc8-1c404e7821e1.png)
Recipe for creation

![Immersive_Conveyor_Recipe_Wrought](https://user-images.githubusercontent.com/13948660/235976128-b131dcd2-dd5d-414d-8bfc-56cca43dd1e8.png)
Wrought Iron Trapdoor

![Immersive_Conveyor_Recipe_Wrought2](https://user-images.githubusercontent.com/13948660/235976167-9de46acf-d0b4-4f0c-a46e-4e16e702dfcd.png)
Wrought Iron Trapdoor

**Comment by thevortex** [comment]
this was an oversight, will get it fixed in next update! thanks!
