### ISSUE TITLE
[crash] 2 mods are gone

### ISSUE THREAD

**Issue by BamsTheSergal** [AllTheMods/tfc#81]
2 mods from curseforge are just outright deleted, so the mods "cartography" and "blaze map" seemed to have been removed from curseforge, meaning the modpack doesnt start because you cant download blaze map, tho interestingly the cartography mod downloaded fine.

**Comment by thevortex** [comment]
sounds like you are trying to run the server pack as the client. try installing the client pack from curseforge. there are no issues with blazemap or cartography
